### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by qingchenkanlu** [mahaoxiang822/Scale-Balanced-Grasp#3]
Traceback (most recent call last):
  File "train.py", line 93, in <module>
    from loss import get_loss
  File "/media/ys/E/code/Scale-Balanced-Grasp-main/models/loss.py", line 22, in <module>
    width_distribution_prior = np.load("statistic/best_width_distribution_robust_32.npy", allow_pickle=True).item()
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'statistic/best_width_distribution_robust_32.npy'

请问一下，是不是缺少了文件？

**Comment by mahaoxiang822** [comment]
Hi, sorry for the mistake and I've update the code. Please feel free to contact me for any questions about our paper and code.

**Comment by qingchenkanlu** [comment]
感谢分享，我在导入的时候又出现了另外一个问题

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 448, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, '\x00'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 93, in <module>
    from loss import get_loss
  File "/media/ys/E/code/Scale-Balanced-Grasp-main/models/loss.py", line 23, in <module>
    width_distribution_prior = np.load("statistic/scale_distribution.npy", allow_pickle=True).item()
  File "/usr/local/lib/python3.7/dist-packages/numpy/lib/npyio.py", line 451, in load
    "Failed to interpret file %s as a pickle" % repr(file)) from e
OSError: Failed to interpret file 'statistic/scale_distribution.npy' as a pickle

是不是文件格式不正确？

**Comment by mahaoxiang822** [comment]
sorry for the mistake, please pull and try again

**Comment by qingchenkanlu** [comment]
非常感谢！现在可以了。请问一下，是否可以公开机器人抓取部分的代码供大家学习？或者我可以参考哪些代码来完成机器人的抓取？

**Comment by mahaoxiang822** [comment]
机器人抓取部分的代码包括相机的感知，抓取点预测（本文部分）和机械臂控制，相关项目还在整理过程中。如果需要参考我推荐[OCRTOC](https://github.com/OCRTOC/OCRTOC_software_package) 可以先在仿真环境中进行尝试再在真实机器人上部署。有问题欢迎通过邮箱 mahaoxiang822@buaa.edu.cn 交流

**Comment by qingchenkanlu** [comment]
好的，谢谢大佬，非常感谢！

**Comment by Kezuoxun** [comment]
您好:
我閱讀了您的paper後，對於您的MSCG方法的設計有極大的興趣。
但由於我目前在進行SBL方法時，在loss.py中發現缺少了statistic/scale_distribution.npy的ground truth 檔案，
請問這個檔案可提供嗎，或是有相關的程式可以做該檔案的生成呢~
# scale distribution prior
scale_distribution_prior = np.load("statistic/scale_distribution.npy", allow_pickle=True).item()
