### ISSUE TITLE
缺少文件 (statistic/scale_distribution.npy)

### ISSUE THREAD

**Issue by Kezuoxun** [mahaoxiang822/Scale-Balanced-Grasp#6]
您好:
我閱讀了您的paper後，對於您的MSCG方法的設計有極大的興趣。
但由於我目前在進行SBL方法時，在loss.py中發現缺少了statistic/scale_distribution.npy的ground truth 檔案(如下)，
請問這個檔案可提供嗎，或是有相關的程式可以做該檔案的生成呢~
# scale distribution prior
scale_distribution_prior = np.load("statistic/scale_distribution.npy", allow_pickle=True).item()

**Comment by mahaoxiang822** [comment]
你好，在主目录下的statistic文件夹中有该文件，您方便检查一下文件路径吗

**Comment by Kezuoxun** [comment]
您好，謝謝您，我沒注意到該檔案已在資料夾中，謝謝您的回覆~
